# Generated by Django 3.0.5 on 2020-04-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_main_abouttxt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='abouttxt',
        ),
    ]
