# Generated by Django 3.0.5 on 2020-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='txt',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.TextField(),
        ),
    ]
