# Generated by Django 3.0.5 on 2020-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200501_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
